### ISSUE TITLE
Add a VScode prompt prompting you to delete the virtual machine files or keep them.

### ISSUE THREAD

**Issue by MikhailBystrov** [Parallels/parallels-vscode-extension#83] opened 2024-06-07 18:34 UTC
**Is your feature request related to a problem? Please describe.**
When we delete a VM using VScode, we leave the files of that VM in our file system.
Create the VM, delete it and notice that the files are left in the file system in the path ~/Applications (Parallels)/<VM_NAME>

**Describe the solution you'd like**
It seems to me that you should add a prompt to VScode that prompts you to delete, or leave files related to the VM being deleted by the user. Just as it is made in PD.

<img width="289" alt="image" src="https://github.com/Parallels/parallels-vscode-extension/assets/41427413/3632a5c2-9ea4-4e4f-bf55-09a8a345e063">

Or I'd prefer to delete these files by default, as I don't see why I'd need these files if I'm using VScode as UI

**Comment by cjlapao** [comment] 2024-06-10 07:18
@MikhailBystrov this seems to be a bug as by default the extension uses prlctl on the background and this should by default delete the files and not keep them. I will check what is the prlctl default behaviour and see if there is any settings.

Any changes will be addressed in the prlctl and not in the VSCode extension

**Comment by cjlapao** [comment] 2024-06-10 12:49
This has been confirmed as a bug in our virtualization engine and it will be dealt there, but this will be open for tracking that internal issue under our VSCode extension

**Closed** 2024-10-16 08:59 UTC
Labels: bug
